### ISSUE TITLE
[BUG] Link output from bootstrap does not work if user has access to multiple tenants

### ISSUE THREAD

**Issue by SimonWahlin** [Azure/sovereign-landing-zone#11]
**Describe the bug**
When the script New-SovereignLandingZone.ps1 is complete, a link to the portal is written to the output. If the deploying user has access to more than one tenant the code `(Get-Tenant).Id` returns multiple tenant ids which would be joined with space.

**To Reproduce**
1. Use an account with access to more than one tenant.
1. Run `./New-SovereignLandingZone.ps1 -parDeployment bootstrap`
2. The link outputted will not be clickable since it contains spaces that are not url encoded.

**Expected behavior**
The link should be clickable in the terminal

**Comment by ugreg** [comment]
@SimonWahlin this issue has been resolved. Please validate against this latest code from main branch.
