### ISSUE TITLE
[BUG] - Error with launch SLZ through Azure DevOps

### ISSUE THREAD

**Issue by pietromariodambrosio** [Azure/sovereign-landing-zone#5]
**Describe the bug**
When using Azure DevOps to launch the New-SovereignLandingZone.ps1 script, it fails and asks for the login, even using `-parAttendedLogin $false`. The script works fine if executed from a local machine, but only after the login.
We followed the guidelines contained in the docs (https://github.com/Azure/sovereign-landing-zone/blob/main/docs/scenarios/Pipeline-Deployments.md), but we are still encountering the same error.
We have a Service Principal with the required permission bound to a Service Connection that we use in our pipeline.

**To Reproduce**
1. Create a Pipeline on Azure DevOps Services (https://dev.azure.com/) with this task:

- task: AzureCLI@2
  inputs:
    azureSubscription: ${{ parameters.SPN_AUTOMATION }}
    scriptType: pscore
    scriptLocation: inlineScript
    inlineScript: |

      Install-Module Az.Resources -Force
      Import-Module -Name Az.Resources
      Get-Module 

      cd SLZ\orchestration\scripts\
      # Execute the SLZ module bootstrap and platform
      # bootstrap deploys the management groups and subscriptions
      pwsh -Command {./New-SovereignLandingZone.ps1 -parAttendedLogin $false -parDeployment bootstrap}
      # platform deploys the resource groups in each of the subscriptions along with the networking resources.
      pwsh -Command {./New-SovereignLandingZone.ps1 -parAttendedLogin $false -parDeployment platform}

the SPN_AUTOMATION parameter refert to our Service Principal

3. in the Task, we lunch a job containing the command `./New-SovereignLandingZone.ps1 -parAttendedLogin $false -parDeployment bootstrap` using a Service Principal, as explained in the aforementioned docs.

**Expected behavior**
The bootstrap deployment correctly starts and finishes.

**Screenshots**
The error we got from the DevOps pipeline is the following:
```
New-AzTenantDeployment: /home/vsts/work/1/s/SLZ/orchestration/scripts/New-Bootstrap.ps1:58
Line |
  58 |              $modDeployBootstrap = New-AzTenantDeployment `
     |                                    ~~~~~~~~~~~~~~~~~~~~~~~~
     | Run Connect-AzAccount to login.

 

Write-Error: /home/vsts/work/1/s/SLZ/orchestration/scripts/New-SovereignLandingZone.ps1:63
Line |
  63 |          $modDeployBootstrap = New-Bootstrap $null $varParameters
     |                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | >>> Validation error occurred during execution . Please try after
     | addressing the error :
     | Microsoft.PowerShell.Commands.WriteErrorException: Error while executing
     | bootstrap deployment command \n  \n at New-Bootstrap,
     | /home/vsts/work/1/s/SLZ/orchestration/scripts/New-Bootstrap.ps1: line 67
     | at <ScriptBlock>,
     | /home/vsts/work/1/s/SLZ/orchestration/scripts/New-SovereignLandingZone.ps1: line 63 at <ScriptBlock>, <No file>: line 1

**Additional context**
Add any other context about the problem here.

**Comment by azure-lm** [comment]
Hello and thank you for submitting this bug report. Apologies this isn't working for you.

The v0.3.1 hotfix released yesterday changed the behavior when using the **parAttendedLogin** parameter and it can be used with 0 instead of $false on Linux-based environments. Can you try invoking the command as such:

`pwsh -Command {./New-SovereignLandingZone.ps1 -parAttendedLogin 0 -parDeployment bootstrap}`

The script will attempt to prompt the user to login when `-parAttendedLogin 0` or `-parAttendedLogin $false` are not provided. On Linux shells, we noticed that $false wasn't being passed as a Boolean (but instead as a string, which we weren't handling), thus causing this problem.

Please let me know if this works for you and I'll update the documentation accordingly.

**Comment by pietromariodambrosio** [comment]
Hello, 
we update the source at the version 0.3.1.
We tried the solution that you suggest, but it doesn't work.


We have the same error:

```
/usr/bin/pwsh -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command . '/home/vsts/work/_temp/azureclitaskscript1698137609868.ps1'

ModuleType Version    PreRelease Name                                ExportedCo
                                                                     mmands
---------- -------    ---------- ----                                ----------
Script     2.13.1                Az.Accounts                         {Add-AzEn…
Script     6.11.2                Az.Resources                        {Export-A…
Manifest   7.0.0.0               Microsoft.PowerShell.Management     {Add-Cont…
Manifest   7.0.0.0               Microsoft.PowerShell.Utility        {Add-Memb…
Script     1.4.7                 PackageManagement                   {Find-Pac…
Script     2.2.5                 PowerShellGet                       {Find-Com…
>>> If you are running this deployment in admin mode and left mouse click in the PowerShell window, a text selection rectangle will appear and deployment will halt. Press the Enter key to continue the deployment.
>>> Bootstrap deployment started
New-AzTenantDeployment: /home/vsts/work/1/s/SLZ/orchestration/scripts/New-Bootstrap.ps1:61
Line |
  61 |                  $modDeployBootstrap = New-AzTenantDeployment `
     |                                        ~~~~~~~~~~~~~~~~~~~~~~~~
     | Run Connect-AzAccount to login.
```


We successfully run this task by change the type of AzureDevOps Task from AZCLI@2 to AzurePowerShell@5


```
The new Azure DevOps task is:

- task: AzurePowerShell@5
  inputs:
    azureSubscription: ${{ parameters.SPN_AUTOMATION }}
    ScriptType: inlineScript
    Inline: |
       Get-Module 
       cd SLZ\orchestration\scripts\

       Get-AzContext

       ./New-SovereignLandingZone.ps1 -parAttendedLogin 0 -parDeployment bootstrap
       ./New-SovereignLandingZone.ps1 -parAttendedLogin 0 -parDeployment platform

    azurePowerShellVersion: LatestVersion
```



Thanks for you support.

Best Regards,
Pietro

**Comment by azure-lm** [comment]
Thanks for providing a resolution process that worked! I'll get this added to the docs.

**Comment by azure-lm** [comment]
We have updated the documentation in v0.3.2 with an example built from the provided snippet.

**Comment by azure-lm** [comment]
Issue has been resolved, closing the item.
