### ISSUE TITLE
Add ItalyNorth Region

### ISSUE THREAD

**Issue by pietromariodambrosio** [Azure/sovereign-landing-zone#7]
**Is your feature request related to a problem? Please describe.**
Is it possible to include Italy North in the allowed regions for the deployment?

We tried to use this code by configuring it with italynorth (region) but it is necessary to change the allowed regions in the yaml and bicep files.

**Describe the solution you'd like**
Integration of the Italian region into the SLZ code

**Comment by azure-lm** [comment]
Hello, this is a bug, and we will be releasing a fix for it on Thursday this week.

Let me know if that timing works for you and if you need a quicker resolution then I'll pull together a relevant git diff.

**Comment by azure-lm** [comment]
We just released v0.3.2 which should resolve this issue. Please try again with the new release.

**Comment by azure-lm** [comment]
Issue has been resolved, closing the item.
