### ISSUE TITLE
[BUG] Wrong description in parameters file

### ISSUE THREAD

**Issue by SimonWahlin** [Azure/sovereign-landing-zone#9]
**Describe the bug**
The description of parameter "parCustomerPolicySets" does not make sense.
[Log Analytics Workspace](https://github.com/Azure/sovereign-landing-zone/blob/bfdd870d8d48dfc7e3710cff4f4c1fff74ae85a6/orchestration/scripts/parameters/sovereignLandingZone.parameters.json#L528)

**To Reproduce**
1. Go to [Log Analytics Workspace](https://github.com/SimonWahlin/sovereign-landing-zone/blob/bfdd870d8d48dfc7e3710cff4f4c1fff74ae85a6/orchestration/scripts/parameters/sovereignLandingZone.parameters.json#L528)
2. Read description

**Expected behavior**
The description should read for example: `Optional array of customer specified policy assignments to the top-level management group.`

**Comment by azure-lm** [comment]
Issue has been resolved, closing the item.
